spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/dealDB"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8091

service:
  integration:
    deal:
      url: "http://localhost:8090/deal"

