spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: "deal"

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

server:
  port: 8380

deal:
  dataPath: "D:/creditConveyor/deal/"