spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "deal"

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    username: yourmail@example.com
    password: somepassword

server:
  port: 8380