name: CI/CD pipeline with Codecov & SonarCloud

on: [push, pull_request]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Build Application with Maven
        working-directory: ./application
        run: mvn -B clean install --file pom.xml

      - name: Build Conveyor with Maven
        working-directory: ./conveyor
        run: mvn -B clean install --file pom.xml

      - name: Build Deal with Maven
        working-directory: ./deal
        run: mvn -B clean install --file pom.xml

      - name: Build Dossier with Maven
        working-directory: ./dossier
        run: mvn -B clean install --file pom.xml

      - name: Build Gateway with Maven
        working-directory: ./gateway
        run: mvn -B clean install --file pom.xml

  sonarcloud:
    name: SonarCloud analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Analyze Application with SonarCloud
        working-directory: ./application
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=vlad777442_spring-boot-credit-system

      - name: Analyze Conveyor with SonarCloud
        working-directory: ./conveyor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=vlad777442_spring-boot-credit-system

      - name: Analyze Deal with SonarCloud
        working-directory: ./deal
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=vlad777442_spring-boot-credit-system

      - name: Analyze Dossier with SonarCloud
        working-directory: ./dossier
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=vlad777442_spring-boot-credit-system

      - name: Analyze Gateway with SonarCloud
        working-directory: ./gateway
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=vlad777442_spring-boot-credit-system

  codecov:
    name: Coverage analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Verify Application with Maven
        working-directory: ./application
        run: mvn -B clean verify

      - name: Application Coverage with Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./application
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: Application

      - name: Verify Conveyor with Maven
        working-directory: ./conveyor
        run: mvn -B clean verify

      - name: Conveyor Coverage with Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./conveyor
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: Conveyor

      - name: Verify Deal with Maven
        working-directory: ./deal
        run: mvn -B clean verify

      - name: Deal Coverage with Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./deal
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: Deal

      - name: Verify Dossier with Maven
        working-directory: ./dossier
        run: mvn -B clean verify

      - name: Dossier Coverage with Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./dossier
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: Dossier

      - name: Verify Gateway with Maven
        working-directory: ./gateway
        run: mvn -B clean verify

      - name: Gateway Coverage with Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./gateway
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: Gateway